Conteudo -> Filme: extend {
    target-arrowhead {
        shape: diamond
    }
}
Conteudo -> Serie: extend {
    target-arrowhead {
        shape: diamond
    }
}  
Filme <-> Diretor {
    source-arrowhead: * 
    target-arrowhead: 1 
}
Filme <-> Ator {
        source-arrowhead: *
        target-arrowhead: *
}  
Usuario <-> Review {
        source-arrowhead: 1
        target-arrowhead: *
}
Usuario <-> Avaliacao {
        source-arrowhead: 1
        target-arrowhead: *
}
Usuario <-> Comentario {
        source-arrowhead: 1
        target-arrowhead: *
}
Moderador <-> Edicao {
        source-arrowhead: 1
        target-arrowhead: *
}
Individuo -> Ator: extend {
    target-arrowhead {
        shape: diamond
    }
} 
Individuo -> Diretor: extend {
    target-arrowhead {
        shape: diamond
    }
} 
Postagem -> Review: extend {
    target-arrowhead {
        shape: diamond
    }
}
Postagem -> Comentario: extend {
    target-arrowhead {
        shape: diamond
    }
}
Usuario -> Moderador: extend {
    target-arrowhead {
        shape: diamond
    }
}

Filme {
    shape: class
    +anoLancamento: int
    +diretor: Diretor
    +duracaoEstimada: int

    +listarAtores(): void
    +atributos(): void
}

Serie {
    shape: class
    +anoInicio: int
    +anoTermino: int
    +qtdTemporadas: int

    +atributos(): void
}

Conteudo {
    shape: class
    +titulo: String
    +faixaEtaria: int
    +avaliacaoMedia: float
    +atores: List<Ator>
    +id: int
}

Individuo {
    shape: class
    +nome: String
    +idade: int
    +paisOrigem: String
    +id: int
}

Diretor {
    shape: class
    +filmesDirigidos: List<Filme>

    +mediaFilmes(): void
    +atributos(): void
}

Ator {
    shape: class
    +filmes: List<Filme>
    +atributos(): void
}

Usuario {
    shape: class
    +nome: String
    +senha: String
    +email: String
    +registro: Date
    +reviews: List<Review>
    +Avaliacoes: List<Avaliacao>
    +comentarios: List<Comentario>

    +atributos(): void
}

Avaliacao {
    shape: class
    +filme: Filme
    +usuario: Usuario
    +nota: float

    +atributos(): void
}

Moderador {
    shape: class
    +historicoEdicoes: List<Edicao>

    +atributos(): void
}

Edicao {
    shape: class
    +moderador: Moderador
    +alvo: Conteudo
    +diff: String
}

Postagem {
    shape: class
    +usuario: Usuario
    +texto: String
    +date: Date
}

Review {
    shape: class
    +avaliacao: int
    +comentarios: List<comentarios>

    +atributos(): void
}

Comentario {
    shape: class
    +review: Review
}

